// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"oa-member/internal/biz"
	"oa-member/internal/conf"
	"oa-member/internal/data"
	"oa-member/internal/server"
	"oa-member/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	memberRepo := data.NewMemberRepo(dataData, logger)
	memberUserCase := biz.NewMemberUserCase(memberRepo, logger)
	memberServiceService := service.NewMemberServiceService(memberUserCase, logger)
	httpServer := server.NewHTTPServer(confServer, memberServiceService, logger)
	grpcServer := server.NewGRPCServer(confServer, memberServiceService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
